# Generated by Django 4.2.11 on 2026-04-17 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True, unique=True
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("link", models.CharField(max_length=255, unique=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(max_length=10)),
                ("voice_settings", models.CharField(max_length=100)),
                (
                    "patient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test_Data",
            fields=[
                ("test_data_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_completed", models.DateTimeField()),
                ("num_total_latency", models.IntegerField()),
                ("mix_total_latency", models.IntegerField()),
                ("avg_num_latency", models.FloatField(default=0)),
                ("avg_mix_latency", models.FloatField(default=0)),
                ("avg_overall_latency", models.FloatField(default=0)),
                ("numeric_correct", models.IntegerField()),
                ("mixed_correct", models.IntegerField()),
                ("numeric_total_stimuli", models.IntegerField(default=0)),
                ("mixed_total_stimuli", models.IntegerField(default=0)),
                ("trial_response_log", models.JSONField(blank=True, default=list)),
                (
                    "test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.test"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stimulus",
            fields=[
                ("stimulus_id", models.AutoField(primary_key=True, serialize=False)),
                ("sequence", models.CharField(max_length=255)),
                (
                    "stimulus_type",
                    models.CharField(
                        choices=[
                            ("digit", "Digit"),
                            ("mixed", "Mixed"),
                            ("practice_digit", "Practice Digit"),
                            ("practice_mixed", "Practice Mixed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("span", models.PositiveIntegerField()),
                ("order_index", models.PositiveIntegerField()),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimuli",
                        to="api.test",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                ("response_id", models.AutoField(primary_key=True, serialize=False)),
                ("clicked_symbol", models.CharField(max_length=5)),
                ("click_order", models.PositiveIntegerField()),
                ("latency_ms", models.IntegerField()),
                ("is_correct", models.BooleanField()),
                ("timestamp", models.DateTimeField()),
                (
                    "stimulus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="api.stimulus",
                    ),
                ),
            ],
        ),
    ]
